# Generated by Django 4.2.3 on 2023-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
